### ISSUE TITLE
关于数据

### ISSUE THREAD

**Issue by chinayuyabin** [TobiasLee/CTEG#3]
请问一下这个是什么文件啊train_src_lbl_oh.npy，和train_src.npy 有什么关系

**Comment by TobiasLee** [comment]
是对应的主题文章类别的 label，用于 Discriminator 算 reward

**Comment by chinayuyabin** [comment]
知道了，多谢大佬指点迷津！




------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 晚上9:59
收件人: "TobiasLee/CTEG"<CTEG@noreply.github.com>; 
抄送: "@My heart will go on."<952167295@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TobiasLee/CTEG] 关于数据 (#3)




是对应的主题文章类别的 label，用于 Discriminator 算 reward

**Comment by TobiasLee** [comment]
很高兴能帮到你~
