### ISSUE TITLE
关于对抗训练速度特别慢的问题

### ISSUE THREAD

**Issue by DarylLei** [TobiasLee/CTEG#4]
感谢您的代码分享！
在运行代码时，对抗训练的生成部分速度特别慢，epoch一次大概要6、7个小时，这样有问题吗？
设备是单个1080gpu，生成部分batch_size 改为32
请问您当时训练一个稳定的模型总共用了多长时间、训练设备是什么样的、参数就是默认参数吗？

**Comment by TobiasLee** [comment]
Hi, 因为 adversarial training 阶段使用的 rollout 在句子长度比较长时间复杂度比较高 所以很慢 这是正常的
你可以把 rollout 的 N 改小一些 来加快速度
我们训练的时候也是 1080Ti ，参数和代码是一致的
